In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

In [2]:
dataset = pd.read_csv('area.csv')

In [3]:
dataset.head()

Area   Perimeter  Eccentricity  Solidity        Mean        Std  Skewness  \
0   818  389.775649      0.912498  0.026805  123.836173  76.258864  0.013893   
1   176  144.976659      0.932594  0.005915  123.926975  76.675130 -0.000127   
2   771  638.290368      0.919126  0.019645  103.232119  84.094740  0.224264   
3   187  163.899495      0.993853  0.340000  129.288148  74.253407 -0.023898   
4   694  440.248737      0.948559  0.021251  124.875226  76.080400  0.008810   

   Kurtosis  Grade  
0 -1.229800      0  
1 -1.226966      0  
2 -1.332574      0  
3 -1.217089      0  
4 -1.230984      0

In [7]:
X = dataset.iloc[:,:8].values
y = dataset['Grade'].values

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB()

In [11]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[3 0 1 2 2 1 2 0 1 1 0 0 1 0 2 0 0 1 0 0 1 1 2 0 0 0 1 1 0 0 1 0 1 1 1 1 1
 0 2 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 1]


In [12]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[0, 3],
       [1, 0],
       [2, 1],
       [3, 2],
       [0, 2]], dtype=int64)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  3  2  1  0]
 [ 3 22  0  0  0]
 [ 3  3  0  0  0]
 [ 5  1  4  0  0]
 [ 8  3  0  0  0]]


In [14]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))  

Correct predictions:  32
False predictions 36


Accuracy of the Naive Bayes Clasification is:  0.47058823529411764
