In [21]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [61]:
df=pd.read_csv('All_features_All_Grades.csv')
print(len(df))
print(df.head())
df.isnull()
df.isnull().sum().sum()
df.dropna(inplace=True)

5778
   Area   Perimeter  Eccentricity  Solidity        Mean        Std  Grade
0   118   86.905592      0.993426  0.011102  128.280951  73.753299      0
1    94   81.935029      0.998492  0.386831  128.433414  73.885214      0
2   189  157.355339      0.620572  0.015067  129.507533  74.188479      0
3   158  118.183766      0.917391  0.012529  128.920380  73.838446      0
4   191  124.840620      0.995318  0.565089  128.528440  73.719059      0


In [62]:
X=dataset.iloc[:,0:5]
y=dataset.iloc[:,6]
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=.2)

In [63]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [64]:
classifi=KNeighborsClassifier(n_neighbors=29,p=5,metric='euclidean')

In [65]:
classifi.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=29, p=5)

In [66]:
y_pred=classifi.predict(X_test)
y_pred

array([0, 0, 2, ..., 0, 0, 0], dtype=int64)

In [67]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[376  21  60   4   0]
 [174  10  25   1   0]
 [255  13  39   5   0]
 [110   9  28   1   0]
 [ 15   2   7   1   0]]


In [68]:
print(f1_score(y_test,y_pred))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].