In [1]:
import numpy as np 

arrr=np.array([1,2,3,4])
print(arrr)

[1 2 3 4]


In [2]:
print(type(arrr))

<class 'numpy.ndarray'>


In [3]:
print(arrr.shape)

(4,)


In [4]:
arrr[3]=10
print(arrr)

[ 1  2  3 10]


In [10]:
arr1=np.array([[1,2,4],[1,2,7],[1,2,6]])
print(arr1)

[[1 2 4]
 [1 2 7]
 [1 2 6]]


In [13]:
arr1[2][2]
print(arr1.shape)

(3, 3)


In [18]:
arr1[2,-1]

6

In [21]:
ars=np.array(['gg','gg','gg'])
arR=np.arange(1,20,1)
print(ars)
print(arR)

['gg' 'gg' 'gg']
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
arl=np.linspace(0,5,10)
print(arl)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [26]:
pp=2*np.random.rand(5)
print(pp)

[1.31283653 0.43456223 1.34415802 1.34401673 1.08019307]


In [29]:
print(np.zeros((2,2,2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [37]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [42]:
arrre=([1,2,3])
print(np.repeat(arrre,2))
print(np.tile(arrre,3))

[1 1 2 2 3 3]
[1 2 3 1 2 3 1 2 3]
