In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

In [2]:
dataset = pd.read_csv('hu.csv')

In [3]:
dataset.head()

Hu moment 1  Hu moment 2  Hu moment 3  Hu moment 4  Hu moment 5  \
0     2.985695     6.954078    10.633049    11.902984   -23.180785   
1     2.977737     6.818544    10.983430    12.248659   -24.603627   
2     3.011518     7.472868    11.064236    12.090032   -23.670170   
3     2.969257     6.814332    11.128081    12.467895    24.302647   
4     3.001156     7.093602    11.200217    11.694102   -23.453287   

   Hu moment 6  Hu moment 7  Grade  
0    16.639311   -23.848990      0  
1    16.928135   -23.872052      0  
2   -15.995767   -24.598209      0  
3   -15.875281    24.669668      0  
4    15.475848    23.200185      0

In [5]:
X = dataset.iloc[:,:7].values
y = dataset['Grade'].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB()

In [10]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[3 0 1 4 2 1 0 0 1 1 3 0 4 3 1 0 0 1 0 0 1 0 3 0 0 2 1 4 2 0 1 0 1 4 1 0 1
 0 2 0 1 3 0 0 0 1 0 1 0 3 0 0 1 0 1 0 1 1 0 0 0 4 1 0 1 1 0 1]


In [11]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[0, 3],
       [1, 0],
       [2, 1],
       [3, 4],
       [0, 2]], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  2  1  2  0]
 [ 9 13  0  1  2]
 [ 1  3  1  1  0]
 [ 3  2  2  1  2]
 [ 6  3  0  1  1]]


In [13]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))  

Correct predictions:  27
False predictions 41


Accuracy of the Naive Bayes Clasification is:  0.39705882352941174
