In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

In [3]:
dataset = pd.read_csv('lbp.csv')

In [4]:
dataset.head()

LBP 0     LBP 1     LBP 2     LBP 3     LBP 4     LBP 5     LBP 6  \
0  0.029444  0.016831  0.015288  0.012037  0.008601  0.008189  0.008663   
1  0.035494  0.023971  0.017202  0.012243  0.009774  0.009177  0.010247   
2  0.024074  0.013889  0.012984  0.010412  0.006770  0.006502  0.006975   
3  0.037963  0.018745  0.019403  0.018477  0.013724  0.011337  0.010494   
4  0.025185  0.015432  0.015123  0.013045  0.008663  0.008621  0.007901   

      LBP 7     LBP 8     LBP 9  ...    LBP 17    LBP 18    LBP 19    LBP 20  \
0  0.011379  0.014218  0.018086  ...  0.015329  0.009012  0.009012  0.010103   
1  0.012140  0.015823  0.019979  ...  0.011934  0.009115  0.009156  0.009650   
2  0.009444  0.010597  0.012531  ...  0.009362  0.006955  0.006132  0.007407   
3  0.012263  0.014568  0.019527  ...  0.013519  0.011049  0.012202  0.014095   
4  0.011708  0.012819  0.016934  ...  0.019280  0.008827  0.009280  0.008663   

     LBP 21    LBP 22    LBP 23    LBP 24    LBP 25  Grade  
0  0.013128  0.017160  0.017263  0.083889  0.304959      0  
1  0.012078  0.016914  0.018745  0.080700  0.372798      0  
2  0.010391  0.012654  0.013930  0.232263  0.255782      0  
3  0.018498  0.021543  0.016317  0.051255  0.334342      0  
4  0.013086  0.014691  0.015288  0.070329  0.287016      0  

[5 rows x 27 columns]

In [5]:
X = dataset.iloc[:,:25].values
y = dataset['Grade'].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB()

In [9]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[0 0 1 2 3 4 2 0 1 1 0 0 2 0 0 0 2 1 2 0 1 1 2 2 0 2 1 4 2 2 1 0 1 4 1 1 1
 2 2 1 0 3 2 0 1 4 2 1 1 2 0 0 1 2 1 0 1 4 2 0 1 2 0 1 1 2 1 1]


In [10]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[0, 0],
       [1, 0],
       [2, 1],
       [3, 2],
       [0, 3]], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 8  2  5  1  0]
 [ 3 18  2  0  2]
 [ 0  3  2  1  0]
 [ 3  0  5  0  2]
 [ 4  1  5  0  1]]


In [12]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))  

Correct predictions:  29
False predictions 39


Accuracy of the Naive Bayes Clasification is:  0.4264705882352941
